# Generated by Django 4.1.4 on 2022-12-26 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propertytypes', '0001_initial'),
        ('currencies', '0001_initial'),
        ('virtualtours', '0001_initial'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_rooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('floors', models.IntegerField(default=0)),
                ('garage', models.IntegerField(default=0)),
                ('parking_lot', models.IntegerField(default=0)),
                ('property_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('land_area', models.DecimalField(decimal_places=1, max_digits=5)),
                ('feature', multiselectfield.db.fields.MultiSelectField(choices=[('balcony', 'balcony'), ('generator', 'generator'), ('garage', 'garage'), ('garden', 'garden'), ('water-tank', 'wat,er-tank'), ('water-pump', 'water-pump'), ('swimming pool', 'swimming pool'), ('clubhouses', 'clubhouses'), ('tennis court', 'tennis court'), ('parking', 'parking'), ('covered parking', 'covered parking'), ('common areas', 'common areas'), ('security', 'security'), ('bike storage', 'bike storage'), ('electric car charing station', 'electric car charing station'), ('barbeque areas', 'barbeque areas'), ('picnic tables', 'picnic tables'), ('elevators', 'elevators'), ('wi-fi', 'wi-fi')], max_length=100)),
                ('year_built', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField()),
                ('is_for_rent', models.BooleanField(default=False)),
                ('rent_price', models.IntegerField()),
                ('is_furnished', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('floor_plan_image1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('floor_plan_image2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('floor_plan_image3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('floor_plan_image4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('floor_plan_image5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='currencies.currency')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='propertytypes.propertytype')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
                ('virtual_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualtours.virtualtour')),
            ],
            options={
                'verbose_name': 'Propertie',
            },
        ),
        migrations.CreateModel(
            name='PropertyMultiplePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
        ),
    ]
