# Generated by Django 4.1.4 on 2022-12-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='selling_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='rent_price',
        ),
    ]
