# Generated by Django 4.1.4 on 2022-12-27 06:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_selling_price_listing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default=2, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='feature',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('balcony', 'balcony'), ('generator', 'generator'), ('garage', 'garage'), ('garden', 'garden'), ('water-tank', 'water-tank'), ('water-pump', 'water-pump'), ('swimming pool', 'swimming pool'), ('clubhouses', 'clubhouses'), ('tennis court', 'tennis court'), ('parking', 'parking'), ('covered parking', 'covered parking'), ('common areas', 'common areas'), ('security', 'security'), ('bike storage', 'bike storage'), ('electric car charing station', 'electric car charing station'), ('barbeque areas', 'barbeque areas'), ('picnic tables', 'picnic tables'), ('elevators', 'elevators'), ('wi-fi', 'wi-fi')], max_length=100),
        ),
    ]
