# Generated by Django 4.1.4 on 2024-08-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_photo_main_alter_listing_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
