# Generated by Django 4.1.4 on 2024-09-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Propertie'},
        ),
    ]
