# Generated by Django 4.1.4 on 2024-04-08 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('subsribed_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
